# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0765e792ae64d0fcc3efff1118ba23df1a7d95e4468c0c4d141dbf21c69261e68cd1a0741144bc7dba5248c0c9ddebb943a0d1f471e5e955f65ef012faac5d8b

test:
  secret_key_base: 456085eb0935d0d48857728bb64b3b16e1546232440287287ec6a1819bb0c102f3cfd8ca79e83bec1b31ab3ec041840e56a3767cc16c759c608be4b95064f268

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
